export const colombiaData = {
    'Amazonas': ['Leticia', 'Puerto Nariño', 'La Chorrera', 'La Pedrera', 'Mirití-Paraná'],
    'Antioquia': ['Medellín', 'Bello', 'Itagüí', 'Envigado', 'Rionegro'],
    'Arauca': ['Arauca', 'Arauquita', 'Saravena', 'Fortul', 'Tame'],
    'Atlántico': ['Barranquilla', 'Soledad', 'Malámbo', 'Sabanalarga', 'Baranoa'],
    'Bolívar': ['Cartagena', 'Magangué', 'Turbaco', 'Arjona', 'Mompós'],
    'Boyacá': ['Tunja', 'Sogamoso', 'Duitama', 'Chiquinquirá', 'Paipa'],
    'Caldas': ['Manizales', 'La Dorada', 'Chinchiná', 'Aguadas', 'Riosucio'],
    'Caquetá': ['Florencia', 'San Vicente del Caguán', 'Puerto Rico', 'Cartagena del Chairá', 'El Doncello'],
    'Casanare': ['Yopal', 'Aguazul', 'Villanueva', 'Tauramena', 'Maní'],
    'Cauca': ['Popayán', 'Santander de Quilichao', 'Puerto Tejada', 'Corinto', 'Guapi'],
    'Cesar': ['Valledupar', 'Aguachica', 'Codazzi', 'La Paz', 'San Alberto'],
    'Chocó': ['Quibdó', 'Istmina', 'Condoto', 'Riosucio', 'Bahía Solano'],
    'Córdoba': ['Montería', 'Cereté', 'Lorica', 'Sahagún', 'Montelíbano'],
    'Cundinamarca': ['Bogotá', 'Soacha', 'Zipaquirá', 'Girardot', 'Facatativá'],
    'Guainía': ['Inírida', 'Cacahual', 'La Guadalupe', 'Mapiripana', 'Morichal'],
    'Guaviare': ['San José del Guaviare', 'Calamar', 'El Retorno', 'Miraflores'],
    'Huila': ['Neiva', 'Pitalito', 'Garzón', 'La Plata', 'Gigante'],
    'La Guajira': ['Riohacha', 'Maicao', 'Albania', 'Dibulla', 'Uribia'],
    'Magdalena': ['Santa Marta', 'Ciénaga', 'Fundación', 'Aracataca', 'El Banco'],
    'Meta': ['Villavicencio', 'Acacías', 'Granada', 'Puerto López', 'San Martín'],
    'Nariño': ['Pasto', 'Tumaco', 'Ipiales', 'Tuquerres', 'Samaniego'],
    'Norte de Santander': ['Cúcuta', 'Ocaña', 'Pamplona', 'Los Patios', 'Tibú'],
    'Putumayo': ['Mocoa', 'Puerto Asís', 'Orito', 'Puerto Caicedo', 'Villagarzón'],
    'Quindío': ['Armenia', 'Montenegro', 'Quimbaya', 'Calarcá', 'La Tebaida'],
    'Risaralda': ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'La Virginia', 'Marsella'],
    'San Andrés y Providencia': ['San Andrés', 'Providencia'],
    'Santander': ['Bucaramanga', 'Floridablanca', 'Girón', 'Piedecuesta', 'Barrancabermeja'],
    'Sucre': ['Sincelejo', 'Corozal', 'San Marcos', 'Since', 'Tolú'],
    'Tolima': ['Ibagué', 'Espinal', 'Melgar', 'Flandes', 'Líbano'],
    'Valle del Cauca': ['Cali', 'Buenaventura', 'Palmira', 'Tuluá', 'Jamundí'],
    'Vaupés': ['Mitú', 'Taraira', 'Pacoa', 'Papunaua', 'Yavaraté'],
    'Vichada': ['Puerto Carreño', 'La Primavera', 'Santa Rosalía', 'Cumaribo']
};
